nelmio_api_doc:
    documentation:
        info:
            title: OSK API Documentation
            description: This is osk api documentation
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)