version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - symfony_network
    depends_on:
      - database
      - test_database

  database:
    image: postgres:16-alpine
    container_name: symfony_db
    environment:
      POSTGRES_DB: osk_symfony
      POSTGRES_USER: osk_symfony
      POSTGRES_PASSWORD: osk_symfony
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - symfony_network

  test_database:
    image: postgres:16-alpine
    container_name: symfony_test_db
    environment:
      POSTGRES_DB: osk_symfony_test
      POSTGRES_USER: osk_symfony
      POSTGRES_PASSWORD: osk_symfony
    volumes:
      - test_database_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - symfony_network

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge

volumes:
  database_data:
    driver: local
  test_database_data:
    driver: local
