version: '3.8'

services:
  # PHP service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - symfony_network
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://symfony:symfony@db:5432/symfony"

  # PostgreSQL service
  db:
    image: postgres:16
    container_name: symfony_db
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - symfony_network

  # Nginx web server (optional, but useful for production-like setup)
  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge

volumes:
  db_data:
    driver: local
